version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql_github_etl
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
    volumes:
      - type: bind
        source: ./data/mysql
        target: /var/lib/mysql